language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install --editable .

before_script:
  - python manage.py migrate djangocms_career

script:
  - python manage.py test djangocms_career

env:
  - DJANGO="Django==1.5.8"
  - DJANGO="Django==1.6.5"
  - DJANGO="Django==1.7.4"
  - DJANGO="Django==1.8.14"
  - DJANGO="Django==1.9.8"
  - DJANGO="Django==1.10"

matrix:
  exclude:
    # Django 1.9 doesn't support Python 3.3
    - python: "3.3"
      env: DJANGO="Django==1.9.8"
    - python: "3.3"
env: DJANGO="Django==1.10"
